@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Oct 30 15:56:49 -0300 2021
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TestBaudRateGenerator_time_synth -key {Post-Synthesis:sim_1:Timing:TestBaudRateGenerator} -tclbatch TestBaudRateGenerator.tcl -view C:/Users/CR/Desktop/arqui/ArquiComp2021/TrabajosPacticos/TP2/UART.Images/TestBaudRateGenerator_time_synth.wcfg -log simulate.log"
call xsim  TestBaudRateGenerator_time_synth -key {Post-Synthesis:sim_1:Timing:TestBaudRateGenerator} -tclbatch TestBaudRateGenerator.tcl -view C:/Users/CR/Desktop/arqui/ArquiComp2021/TrabajosPacticos/TP2/UART.Images/TestBaudRateGenerator_time_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
